POST https://api.weixin.qq.com/wxaapi/broadcast/role/addrole?access_token=45_gEIjLAbUMbvrEYfPUVkhJ0qtZ3PfpTacDjwvlJXxafYQLsvNmO-8vXWSNuQOLLnL7MUc5f5S0-S86cf4CjJAiOakFTwUAuVLVgrWoLEfaICOuyfYhr75XQY0egqfkKiRr71mjpQbGl92s_A2RYFhAGDHOV

{
  username:"jiaqiai_",
  role:"1"
}

###

POST https://srvms.100xsys.cn/health/select/srvhealth_store_list_select
Content-Type: application/json

{"serviceName":"srvhealth_store_list_select","colNames":["*"],"condition":[{"colName":"audit_status","ruleType":"eq","value":"正常"}],"page":{"pageNo":1,"rownumber":10}}

###

POST https://srvms.100xsys.cn/health/select/srvhealth_store_mgmt_select HTTP/1.1
Content-Type: application/json
bx_auth_ticket: xabxdzkj-f36c6868-1e2c-4e95-940a-6186b77e4f8b

{"colNames":["id","store_no","name","introduction","image","logo","type","telephone","address","longitude","latitude","kefu_unread_msg","kefu_unack_msg","member_session_no","member_session_name","barcode_pic"],"condition":[{"colName":"store_no","ruleType":"eq","value":"S20210227032"}],"page":{"pageNo":1,"rownumber":1},"serviceName":"srvhealth_store_mgmt_select"}

